### ISSUE TITLE
Shaped Laser Source

### ISSUE THREAD

**Issue by maxcarrat90** [ansys/pyadditive#274]
### 📝 Description of the feature

To simulate a multimode laser beam, classical Gaussian heat source cannot be used. In fact, multimode laser sources use higher powers distributed on larger heat affected areas, requiring a non-gaussian heat source model to be correctly simulated. Such a kind of energy input seems to be a very promising approach in PBF-LB/M to process infill regions and large components; however, thorough numerical studies are required to understand the complex relationships occurring between multimode laser parameters, material microstructure, and component properties. 

### 💡 Steps for implementing the feature

Introduce a function to add user-defined laser heat source models.

**Comment by pkrull-ansys** [comment]
Unfortunately, this is a solver related issue that is beyond the scope of this library at this time. The solver does not have the capability to incorporate a user laser model and such a feature is not currently planned.
